[programs.Devnet]
mpl-hybrid = "MPL4o4wMzndgh8T1NVDxELQCj5UQfYTYEkabX3wNKtb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[profile.release]
overflow-checks = true # Enable integer overflow checks.
strip = true           # Automatically strip symbols from the binary.
opt-level = 3          # Optimize for speed.
lto = true
codegen-units = 1
